### ISSUE TITLE
pg_query.parser.ParseError for OUT parameters

### ISSUE THREAD

**Issue by pashagolub** [lelit/pg_query#8]
Please, consider function definition in the code:
```
from pg_query import Node, parse_plpgsql
s = '''CREATE OR REPLACE FUNCTION "get_ip_location" (IN ip_address text,
	OUT country varchar,
	OUT isp varchar,
	OUT ip_type varchar,
	OUT latitude float4,
	OUT longitude float4) 	
RETURNS record AS
$BODY$
declare
    ip_number bigint;
  begin
      select foo.country,foo.isp,foo.ip_type,foo.latitude,foo.longitude
      from batch_foo.ip_location foo
      where ip_range @> ip_number
      into
  country,
  isp,
  ip_type,
  latitude,
  longitude;
  return;
  end
$BODY$
	LANGUAGE plpgsql;'''
	
print(s)
root = Node(parse_plpgsql(s))
for node in root.traverse():
	print(node)
```

Output: 

```
pasha@jp0sq32:~/PyEnvironments$ python3 hello.py
...
Traceback (most recent call last):
  File "hello.py", line 28, in <module>
    root = Node(parse_plpgsql(s))
  File "pg_query/parser.pyx", line 98, in pg_query.parser.parse_plpgsql
pg_query.parser.ParseError: "country" is not a known variable, at location 0
```

**Comment by lelit** [comment]
See issue #5, hopefully things will change sooner or later.

**Comment by pashagolub** [comment]
Oouch, I see. I thought you pop up all structures you get from `libpg_query` without any changes...

**Comment by lelit** [comment]
Yes, that's what basically happens, but the standalone plpgsql parser is not ready yet.
Closing as duplicate.
